### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by ghostnumber7** [Unit-X/srt_to_udp_server#2]
Build fails with `error: 'NetworkConnection' was not declared in this scope` due to [this](https://github.com/andersc/cppSRTWrapper/commit/b8ab0c5eea41d5627a86fb4b11ee9e812cb8e39f) change in cppSRTWrapper dependency

**Comment by andersc** [comment]
Thanks for correcting!

**Comment by sfahadshahzad** [comment]
Hi,

I am trying to build on Ubuntu 22.04 and getting errors;

In file included from /home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:10:
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:88:52: error: ‘std::shared_ptr’ has not been declared
   88 |                      const std::string& lPsk = "", std::shared_ptr<NetworkConnection> pCtx = {});
      |                                                    ^~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:88:67: error: expected ‘,’ or ‘...’ before ‘<’ token
   88 |                      const std::string& lPsk = "", std::shared_ptr<NetworkConnection> pCtx = {});
      |                                                                   ^
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:105:22: error: ‘std::shared_ptr’ has not been declared
  105 |                      std::shared_ptr<NetworkConnection> &rpCtx, int lMtu, const std::string& lPsk = "");
      |                      ^~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:105:37: error: expected ‘,’ or ‘...’ before ‘<’ token
  105 |                      std::shared_ptr<NetworkConnection> &rpCtx, int lMtu, const std::string& lPsk = "");
      |                                     ^
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:147:72: error: ‘shared_ptr’ is not a member of ‘std’
  147 |     getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)> &rFunction);
      |                                                                        ^~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:31:1: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
   30 | #include "srt/srtcore/srt.h"
  +++ |+#include <memory>
   31 | 
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:147:83: error: template argument 2 is invalid
  147 |     getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)> &rFunction);
      |                                                                                   ^~~~~~~~~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:147:83: error: template argument 4 is invalid
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:147:72: error: ‘shared_ptr’ is not a member of ‘std’
  147 |     getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)> &rFunction);
      |                                                                        ^~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:147:72: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:147:100: error: template argument 2 is invalid
  147 |     getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)> &rFunction);
      |                                                                                                    ^~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:147:100: error: template argument 4 is invalid
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:147:72: error: ‘shared_ptr’ is not a member of ‘std’
  147 |     getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)> &rFunction);
      |                                                                        ^~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:147:72: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:147:100: error: template argument 2 is invalid
  147 |     getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)> &rFunction);
      |                                                                                                    ^~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:147:100: error: template argument 4 is invalid
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:147:47: error: invalid template-id
  147 |     getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)> &rFunction);
      |                                               ^~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:147:72: error: ‘shared_ptr’ is not a member of ‘std’
  147 |     getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)> &rFunction);
      |                                                                        ^~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:147:72: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:147:105: error: template argument 1 is invalid
  147 |     getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)> &rFunction);
      |                                                                                                         ^
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:147:47: error: class template placeholder ‘std::map’ not permitted in this context
  147 |     getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)> &rFunction);
      |                                               ^~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:150:24: error: ‘shared_ptr’ is not a member of ‘std’
  150 |     std::function<std::shared_ptr<NetworkConnection>(struct sockaddr &rSin,
      |                        ^~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:150:24: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:150:52: error: template argument 1 is invalid
  150 |     std::function<std::shared_ptr<NetworkConnection>(struct sockaddr &rSin,
      |                                                    ^
In file included from /home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:10:
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:154:29: error: ‘shared_ptr’ is not a member of ‘std’
  154 |                        std::shared_ptr<NetworkConnection> &rpCtx, SRTSOCKET lSocket)> receivedData = nullptr;
      |                             ^~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:154:29: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:154:84: error: expression list treated as compound expression in functional cast [-fpermissive]
  154 |                        std::shared_ptr<NetworkConnection> &rpCtx, SRTSOCKET lSocket)> receivedData = nullptr;
      |                                                                                    ^
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:154:85: error: template argument 1 is invalid
  154 |                        std::shared_ptr<NetworkConnection> &rpCtx, SRTSOCKET lSocket)> receivedData = nullptr;
      |                                                                                     ^
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:158:29: error: ‘shared_ptr’ is not a member of ‘std’
  158 |                        std::shared_ptr<NetworkConnection> &rCtx, SRTSOCKET lSocket)> receivedDataNoCopy = nullptr;
      |                             ^~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:158:29: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:158:83: error: expression list treated as compound expression in functional cast [-fpermissive]
  158 |                        std::shared_ptr<NetworkConnection> &rCtx, SRTSOCKET lSocket)> receivedDataNoCopy = nullptr;
      |                                                                                   ^
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:158:84: error: template argument 1 is invalid
  158 |                        std::shared_ptr<NetworkConnection> &rCtx, SRTSOCKET lSocket)> receivedDataNoCopy = nullptr;
      |                                                                                    ^
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:161:29: error: ‘shared_ptr’ is not a member of ‘std’
  161 |     std::function<void(std::shared_ptr<NetworkConnection> &rCtx,
      |                             ^~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:161:29: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:161:60: error: ‘rCtx’ was not declared in this scope
  161 |     std::function<void(std::shared_ptr<NetworkConnection> &rCtx,
      |                                                            ^~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:162:71: error: expression list treated as compound expression in functional cast [-fpermissive]
  162 |                                                      SRTSOCKET lSocket)> clientDisconnected = nullptr;
      |                                                                       ^
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:162:72: error: template argument 1 is invalid
  162 |                                                      SRTSOCKET lSocket)> clientDisconnected = nullptr;
      |                                                                        ^
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:201:30: error: ‘shared_ptr’ is not a member of ‘std’
  201 |     std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> mClientList = {};
      |                              ^~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:201:30: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:201:41: error: template argument 2 is invalid
  201 |     std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> mClientList = {};
      |                                         ^~~~~~~~~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:201:41: error: template argument 4 is invalid
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:201:58: error: expected unqualified-id before ‘>’ token
  201 |     std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> mClientList = {};
      |                                                          ^~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:203:10: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
  203 |     std::shared_ptr<NetworkConnection> mClientContext = nullptr;
      |          ^~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:203:5: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
  203 |     std::shared_ptr<NetworkConnection> mClientContext = nullptr;
      |     ^~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:204:10: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
  204 |     std::shared_ptr<NetworkConnection> mConnectionContext = nullptr;
      |          ^~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:204:5: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
  204 |     std::shared_ptr<NetworkConnection> mConnectionContext = nullptr;
      |     ^~~
In file included from /home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:10:
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:88:52: error: default argument missing for parameter 8 of ‘bool SRTNet::startServer(const string&, uint16_t, int, int32_t, int, int, const string&, int)’
   88 |                      const std::string& lPsk = "", std::shared_ptr<NetworkConnection> pCtx = {});
      |                                                    ^~~~~~~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:88:41: note: ...following parameter 7 which has a default argument
   88 |                      const std::string& lPsk = "", std::shared_ptr<NetworkConnection> pCtx = {});
      |                      ~~~~~~~~~~~~~~~~~~~^~~~~~~~~
In file included from /home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:10:
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:154:102: error: cannot convert ‘std::nullptr_t’ to ‘int’ in initialization
  154 |                        std::shared_ptr<NetworkConnection> &rpCtx, SRTSOCKET lSocket)> receivedData = nullptr;
      |                                                                                                      ^~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:158:107: error: cannot convert ‘std::nullptr_t’ to ‘int’ in initialization
  158 |                        std::shared_ptr<NetworkConnection> &rCtx, SRTSOCKET lSocket)> receivedDataNoCopy = nullptr;
      |                                                                                                           ^~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.h:162:95: error: cannot convert ‘std::nullptr_t’ to ‘int’ in initialization
  162 |                                                      SRTSOCKET lSocket)> clientDisconnected = nullptr;
      |                                                                                               ^~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp: In member function ‘void SRTNet::closeAllClientSockets()’:
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:23:25: error: ‘mClientList’ was not declared in this scope; did you mean ‘mClientListMtx’?
   23 |     for (auto &rClient: mClientList) {
      |                         ^~~~~~~~~~~
      |                         mClientListMtx
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:27:31: error: expression cannot be used as a function
   27 |             clientDisconnected(rClient.second, lSocket);
      |             ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:33:5: error: ‘mClientList’ was not declared in this scope; did you mean ‘mClientListMtx’?
   33 |     mClientList.clear();
      |     ^~~~~~~~~~~
      |     mClientListMtx
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp: At global scope:
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:47:51: error: ‘std::shared_ptr’ has not been declared
   47 |                          const std::string& lPsk, std::shared_ptr<NetworkConnection> pCtx) {
      |                                                   ^~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:47:66: error: expected ‘,’ or ‘...’ before ‘<’ token
   47 |                          const std::string& lPsk, std::shared_ptr<NetworkConnection> pCtx) {
      |                                                                  ^
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp: In member function ‘bool SRTNet::startServer(const string&, uint16_t, int, int32_t, int, int, const string&, int)’:
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:69:10: error: ‘clientConnected’ was not declared in this scope; did you mean ‘clientDisconnected’?
   69 |     if (!clientConnected) {
      |          ^~~~~~~~~~~~~~~
      |          clientDisconnected
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:74:5: error: ‘mConnectionContext’ was not declared in this scope
   74 |     mConnectionContext = pCtx; //retain the optional context
      |     ^~~~~~~~~~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:74:26: error: ‘pCtx’ was not declared in this scope
   74 |     mConnectionContext = pCtx; //retain the optional context
      |                          ^~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp: In member function ‘void SRTNet::serverEventHandler()’:
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:195:38: error: ‘mClientList’ was not declared in this scope; did you mean ‘mClientListMtx’?
  195 |                     auto lIterator = mClientList.find(lThisSocket);
      |                                      ^~~~~~~~~~~
      |                                      mClientListMtx
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:204:43: error: expression cannot be used as a function
  204 |                         clientDisconnected(lCtx, lThisSocket);
      |                         ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:208:57: error: ‘mClientList’ was not declared in this scope; did you mean ‘mClientListMtx’?
  208 |                     receivedData(pointer, lThisMSGCTRL, mClientList.find(lThisSocket)->second, lThisSocket);
      |                                                         ^~~~~~~~~~~
      |                                                         mClientListMtx
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:208:33: error: expression cannot be used as a function
  208 |                     receivedData(pointer, lThisMSGCTRL, mClientList.find(lThisSocket)->second, lThisSocket);
      |                     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:210:69: error: ‘mClientList’ was not declared in this scope; did you mean ‘mClientListMtx’?
  210 |                     receivedDataNoCopy(lMsg, lResult, lThisMSGCTRL, mClientList.find(lThisSocket)->second, lThisSocket);
      |                                                                     ^~~~~~~~~~~
      |                                                                     mClientListMtx
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:210:39: error: expression cannot be used as a function
  210 |                     receivedDataNoCopy(lMsg, lResult, lThisMSGCTRL, mClientList.find(lThisSocket)->second, lThisSocket);
      |                     ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp: In member function ‘void SRTNet::waitForSRTClient()’:
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:241:93: error: ‘mConnectionContext’ was not declared in this scope
  241 |         auto lCtx = clientConnected(*(struct sockaddr *) &lTheir_addr, lNewSocketCandidate, mConnectionContext);
      |                                                                                             ^~~~~~~~~~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:241:21: error: ‘clientConnected’ was not declared in this scope; did you mean ‘clientDisconnected’?
  241 |         auto lCtx = clientConnected(*(struct sockaddr *) &lTheir_addr, lNewSocketCandidate, mConnectionContext);
      |                     ^~~~~~~~~~~~~~~
      |                     clientDisconnected
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:246:13: error: ‘mClientList’ was not declared in this scope; did you mean ‘mClientListMtx’?
  246 |             mClientList[lNewSocketCandidate] = lCtx;
      |             ^~~~~~~~~~~
      |             mClientListMtx
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp: At global scope:
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:259:81: error: ‘shared_ptr’ is not a member of ‘std’
  259 | void SRTNet::getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)>& rFunction) {
      |                                                                                 ^~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:12:1: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
   11 | #include "SRTNetInternal.h"
  +++ |+#include <memory>
   12 | 
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:259:92: error: template argument 2 is invalid
  259 | void SRTNet::getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)>& rFunction) {
      |                                                                                            ^~~~~~~~~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:259:92: error: template argument 4 is invalid
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:259:81: error: ‘shared_ptr’ is not a member of ‘std’
  259 | void SRTNet::getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)>& rFunction) {
      |                                                                                 ^~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:259:81: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:259:109: error: template argument 2 is invalid
  259 | void SRTNet::getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)>& rFunction) {
      |                                                                                                             ^~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:259:109: error: template argument 4 is invalid
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:259:81: error: ‘shared_ptr’ is not a member of ‘std’
  259 | void SRTNet::getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)>& rFunction) {
      |                                                                                 ^~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:259:81: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:259:109: error: template argument 2 is invalid
  259 | void SRTNet::getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)>& rFunction) {
      |                                                                                                             ^~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:259:109: error: template argument 4 is invalid
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:259:56: error: invalid template-id
  259 | void SRTNet::getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)>& rFunction) {
      |                                                        ^~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:259:81: error: ‘shared_ptr’ is not a member of ‘std’
  259 | void SRTNet::getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)>& rFunction) {
      |                                                                                 ^~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:259:81: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:259:114: error: template argument 1 is invalid
  259 | void SRTNet::getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)>& rFunction) {
      |                                                                                                                  ^
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:259:56: error: class template placeholder ‘std::map’ not permitted in this context
  259 | void SRTNet::getActiveClients(const std::function<void(std::map<SRTSOCKET, std::shared_ptr<NetworkConnection>> &)>& rFunction) {
      |                                                        ^~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp: In member function ‘void SRTNet::getActiveClients(const std::function<void(...)>&)’:
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:261:15: error: ‘mClientList’ was not declared in this scope; did you mean ‘mClientListMtx’?
  261 |     rFunction(mClientList);
      |               ^~~~~~~~~~~
      |               mClientListMtx
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp: At global scope:
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:271:26: error: ‘std::shared_ptr’ has not been declared
  271 |                          std::shared_ptr<NetworkConnection> &rpCtx,
      |                          ^~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:271:41: error: expected ‘,’ or ‘...’ before ‘<’ token
  271 |                          std::shared_ptr<NetworkConnection> &rpCtx,
      |                                         ^
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp: In member function ‘bool SRTNet::startClient(const string&, uint16_t, int, int32_t, int, int)’:
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:280:5: error: ‘mClientContext’ was not declared in this scope
  280 |     mClientContext = rpCtx;
      |     ^~~~~~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:280:22: error: ‘rpCtx’ was not declared in this scope
  280 |     mClientContext = rpCtx;
      |                      ^~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:316:60: error: ‘lMtu’ was not declared in this scope
  316 |     lResult = srt_setsockflag(mContext, SRTO_PAYLOADSIZE, &lMtu, sizeof(lMtu));
      |                                                            ^~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:322:9: error: ‘lPsk’ was not declared in this scope
  322 |     if (lPsk.length()) {
      |         ^~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp: In member function ‘void SRTNet::clientWorker()’:
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:386:36: error: ‘mClientContext’ was not declared in this scope
  386 |                 clientDisconnected(mClientContext, mContext);
      |                                    ^~~~~~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:386:35: error: expression cannot be used as a function
  386 |                 clientDisconnected(mClientContext, mContext);
      |                 ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:391:48: error: ‘mClientContext’ was not declared in this scope
  391 |             receivedData(lpData, lThisMSGCTRL, mClientContext, mContext);
      |                                                ^~~~~~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:391:25: error: expression cannot be used as a function
  391 |             receivedData(lpData, lThisMSGCTRL, mClientContext, mContext);
      |             ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:393:61: error: ‘mClientContext’ was not declared in this scope
  393 |             receivedDataNoCopy(lMsg, lResult, lThisMSGCTRL, mClientContext, mContext);
      |                                                             ^~~~~~~~~~~~~~
/home/administrator/srt_to_udp_server/srtwrap/SRTNet.cpp:393:31: error: expression cannot be used as a function
  393 |             receivedDataNoCopy(lMsg, lResult, lThisMSGCTRL, mClientContext, mContext);
      |             ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gmake[6]: *** [CMakeFiles/srtnet.dir/build.make:76: CMakeFiles/srtnet.dir/SRTNet.cpp.o] Error 1
gmake[5]: *** [CMakeFiles/Makefile2:193: CMakeFiles/srtnet.dir/all] Error 2
gmake[4]: *** [CMakeFiles/Makefile2:200: CMakeFiles/srtnet.dir/rule] Error 2
gmake[3]: *** [Makefile:176: srtnet] Error 2
gmake[2]: *** [CMakeFiles/project_cppsrtwrapp.dir/build.make:86: project_cppsrtwrapp-prefix/src/project_cppsrtwrapp-stamp/project_cppsrtwrapp-build] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/project_cppsrtwrapp.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

Regards,

Fahad

**Comment by andersc** [comment]
@sfahadshahzad 

The build error on ubuntu 22.04 is now fixed.

/A
